name: self_management_app
description: "Aplikasi mobile untuk membantu pengguna mengatur waktu, kebiasaan, dan aktivitas harian."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Database
  shared_preferences: ^2.2.2

  # Notifications & Timezone
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  # UI & Utility
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true